app: 
  max-msgs-per-day : 20
  jwt-secret: ${PB_JWT_SECRET}
  code-expiry-minutes: 10
  jwt-expiration-days: 2

    
server : 
  port: ${PB_PORT:8080}
  error:
    include-message: always
spring:
  application:
    name: paranoia-zone
  datasource:
    url: jdbc:postgresql://${PB_URL_HOST:localhost}:5432/picbooker
    username: ${PB_DB_USERNAME:postgres}
    password: ${PB_DB_PASSWORD:admin}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${PB_GOOGLE_CLIENT_ID}
            client-secret: ${PB_GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: ${PB_BASE_URL}/api/auth/oauth2/code/google
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            refresh-token-uri: https://www.googleapis.com/oauth2/v4/token

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${PB_EMAIL_USERNAME}
    password: ${PB_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


